In [1]:
import pandas as pd

In [2]:
df_2000=pd.read_csv("ASDR2000_clean.csv")
df_2010=pd.read_csv("ASDR2010_clean.csv")
df_2016=pd.read_csv("ASDR2000_clean.csv")

In [3]:
df_2000.columns = df_2000.columns.map(lambda x: str(x) + '_2000' if (x!= "6") else "Country")
df_2010.columns = df_2010.columns.map(lambda x: str(x) + '_2010' if (x!= "6") else "Country")
df_2016.columns = df_2016.columns.map(lambda x: str(x) + '_2016' if (x!= "6") else "Country")

In [4]:
df_2000.head()

,Country,Population ('000) (2) _2000,All Causes _2000,"Communicable, maternal, perinatal and nutritional conditions _2000",A. Infectious and parasitic diseases _2000,1. Tuberculosis _2000,2. STDs excluding HIV _2000,a. Syphilis_2000,b. Chlamydia_2000,c. Gonorrhoea_2000,...,3. Falls _2000,"4. Fire, heat and hot substances _2000",5. Drowning _2000,6. Exposure to mechanical forces _2000,7. Natural disasters _2000,8. Other unintentional injuries _2000,B. Intentional injuries _2000,1. Self-harm _2000,2. Interpersonal violence _2000,3. Collective violence and legal intervention _2000
0,Afghanistan,20094,1617.4600,559.55890,315.09060,170.715200,3.567795,3.491298,0.0144806,0.0415336,...,12.863450,1.932442,10.292520,9.982976,.,11.572540,65.123380,8.136609,10.058440,46.92833
1,Albania,3122,766.3497,50.52316,8.43844,1.032880,0.0677191,0.0520935,0.002537,0.00904,...,2.481182,0.902035,3.333463,6.822275,.,10.462750,12.107270,5.826388,6.081221,0.199659
2,Algeria,31184,814.9004,112.55070,37.69140,14.217780,1.127685,1.099142,0.0054975,0.0155686,...,5.631764,3.560195,3.504731,3.019907,0.1963918,6.594805,18.634160,4.722150,7.421035,6.49097
3,Angola,16441,2014.8450,1139.89200,707.68330,145.730600,9.489314,8.96058,0.100591,0.2844356,...,14.715950,10.136160,16.768790,9.095646,0.6190613,20.540770,42.319970,13.892360,14.190630,14.23697
4,Antigua and Barbuda,84,779.1912,93.01495,34.33326,0.446008,0.0409437,0.038385,0.0007684,0.0011098,...,1.567318,2.215903,6.677111,1.488337,.,16.086200,6.423789,2.077088,3.976848,0.3698522

In [5]:
df_merge=df_2000.merge(df_2010, how='left', on='Country', suffixes=(False, False))

In [6]:
df_merge_final=df_merge.merge(df_2016, how='left', on='Country', suffixes=(False, False))

In [15]:
df_merge_final.to_csv("ASDR_merge.csv")

In [7]:
df_merge_final.head()

,Country,Population ('000) (2) _2000,All Causes _2000,"Communicable, maternal, perinatal and nutritional conditions _2000",A. Infectious and parasitic diseases _2000,1. Tuberculosis _2000,2. STDs excluding HIV _2000,a. Syphilis_2000,b. Chlamydia_2000,c. Gonorrhoea_2000,...,3. Falls _2016,"4. Fire, heat and hot substances _2016",5. Drowning _2016,6. Exposure to mechanical forces _2016,7. Natural disasters _2016,8. Other unintentional injuries _2016,B. Intentional injuries _2016,1. Self-harm _2016,2. Interpersonal violence _2016,3. Collective violence and legal intervention _2016
0,Afghanistan,20094,1617.4600,559.55890,315.09060,170.715200,3.567795,3.491298,0.0144806,0.0415336,...,12.863450,1.932442,10.292520,9.982976,.,11.572540,65.123380,8.136609,10.058440,46.92833
1,Albania,3122,766.3497,50.52316,8.43844,1.032880,0.0677191,0.0520935,0.002537,0.00904,...,2.481182,0.902035,3.333463,6.822275,.,10.462750,12.107270,5.826388,6.081221,0.199659
2,Algeria,31184,814.9004,112.55070,37.69140,14.217780,1.127685,1.099142,0.0054975,0.0155686,...,5.631764,3.560195,3.504731,3.019907,0.1963918,6.594805,18.634160,4.722150,7.421035,6.49097
3,Angola,16441,2014.8450,1139.89200,707.68330,145.730600,9.489314,8.96058,0.100591,0.2844356,...,14.715950,10.136160,16.768790,9.095646,0.6190613,20.540770,42.319970,13.892360,14.190630,14.23697
4,Antigua and Barbuda,84,779.1912,93.01495,34.33326,0.446008,0.0409437,0.038385,0.0007684,0.0011098,...,1.567318,2.215903,6.677111,1.488337,.,16.086200,6.423789,2.077088,3.976848,0.3698522

In [11]:
df_hdi=pd.read_csv("HDI_countries.csv", encoding = "ISO-8859-1")

In [12]:
df_hdi.head()

                                                                                                                                                                                                                                                                                 Human development index (HDI)
HDI Rank (2017) Country      1990.000 1991.000 1992.000 1993.000 1994.000 1995.000 1996.000 1997.000 1998.000 1999.000 2000.000 2001.000 2002.000 2003.000 2004.000 2005.000 2006.000 2007.000 2008.000 2009.000 2010.000 2011.000 2012.000 2013.000 2014.000 2015.000 2016.000                       2017.000
168              Afghanistan NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      0.373    0.383    0.398    0.408    0.417    0.429    0.437    0.453    0.463    0.471    0.482    0.487    0.491    0.493    0.494                             0.498
68               Albania     0.645    0.626    0.610    0.613    0.619    0.632    0.641    0.641    0.652    0.662    0.669    0.676    0.682    0.689    0.694    0.704    0.711    0.720    0.724    0.729    0.741    0.752    0.767    0.771    0.773    0.776    0.782                             0.785
85               Algeria     0.577    0.581    0.587    0.591    0.595    0.600    0.608    0.617    0.627    0.636    0.644    0.653    0.664    0.674    0.684    0.692    0.698    0.707    0.709    0.719    0.729    0.736    0.740    0.745    0.747    0.749    0.753                             0.754
35               Andorra     NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN      0.759    0.767    0.780    0.820    0.826    0.819    0.829    0.829    0.831    0.830    0.828    0.827    0.849    0.850    0.853    0.854    0.856                             0.858

In [14]:
list(df_hdi.columns)

['Human development index (HDI)']